### ISSUE TITLE
Error parsing metadata: No option 'author' in section: 'general'

### ISSUE THREAD

**Issue by anitagraser** [akbargumbira/qgis_resources_sharing#27]
When trying to install the plugin from the QGIS plugin repo, I get the following error

![screenshot 2016-08-20 15 41 11](https://cloud.githubusercontent.com/assets/590385/17831571/babb26f0-66ec-11e6-85fd-552a4f9a3bed.png)

**Comment by akbargumbira** [comment]
Can you try to reload the repositories in the Settings tab?

**Comment by akbargumbira** [comment]
I am sorry, missread it, I thought you had problems when installing
collections. Can you describe your machine? (e.g if you have the plugin
installed before)

On Aug 20, 2016 3:58 PM, "Akbar Gumbira" <akbargumbira@gmail.com> wrote:

Can you try to reload the repositories in the Settings tab?

**Comment by anitagraser** [comment]
Yes, I have a manually installed copy of the plugin in C:\Users\Anita\.qgis2\python\plugins\qgis_resources_sharing-master

The repo version is put into C:\Users\Anita\.qgis2\python\plugins\qgis_resource_sharing

**Comment by anitagraser** [comment]
I removed the old manually installed version and tried again. Now it's fine. Sorry for the noise.

**Comment by akbargumbira** [comment]
It should be fine having both plugins (I have it on my machine). But perhaps your github plugin one was outdated and instead of activating the plugin from the repo, you activated the plugin from github? (You need to carefully look at the description of the plugin when you activate it as they both have the same icon)
