### ISSUE TITLE
[Qgis <2.12] Error loading plugin / QgsAuthConfigSelect 

### ISSUE THREAD

**Issue by LCacheux68224** [akbargumbira/qgis_resources_sharing#35]
QgsAuthConfigSelect is not available in Qgis before version 2.12 if I am right, so the plugin cannot be installed for example in Qgis 2.8.
If QgsAuthConfigSelect is absolutely necessary, qgisMinimumVersion should be 2.12 in metadata.txt and not 2.0

**Comment by akbargumbira** [comment]
Hi @LCacheux68224 thanks, yes you're right. It's only available from QGIS 2.2. Instead of restricting the plugin to only users with QGIS >= 2.12 (from metadata.txt), I just disabled the feature to add authentication for users with QGIS < 2.12 (the only thing that they can't do is to add a remote zip repository that has authentication behind it)
