### ISSUE TITLE
Buttons for Open - Uninstall - Install have odd spacing/placement

### ISSUE THREAD

**Issue by elpaso** [akbargumbira/qgis_resources_sharing#4]
Low priority: don't loose time on this now, leave it for final polishing.

I'm not sure about twhat's the best placement but this seems not so natural to me.

![image](https://cloud.githubusercontent.com/assets/142164/16680359/2f050bbe-44ee-11e6-9ee6-c13bb5f1ed5c.png)

**Comment by akbargumbira** [comment]
ok thanks. Any thought from @anitagraser for the UI perspective?

**Comment by anitagraser** [comment]
So far, UI is very much like Plugin Manager. That's good because people are used to it.

On first sight, I'm not 100% sure what the Open button does. Does it open the folder where the resources were downloaded? Maybe call it Open folder. 

Couldn't test more because of this error when clicking Install:

![screenshot 2016-07-09 10 28 21](https://cloud.githubusercontent.com/assets/590385/16706949/e26b3094-45bf-11e6-9b71-4516ba4b6dea.png)

**Comment by akbargumbira** [comment]
Hmm, I definitely need to check against Windows (will think how to grab windows machine first)

**Comment by akbargumbira** [comment]
I changed the Open button to 'Open folder' and move the Uninstall to be placed side by side with Install

**Comment by havatv** [comment]
With @akbargumbira's update, I think this can be closed. I agree with @anitagraser that similarity with the plugin manager UI is not a bad thing.
